### ISSUE TITLE
How much CUDA memory do we need?

### ISSUE THREAD

**Issue by rxmao** [lqtrung1998/mwp_ReFT#12]
I use one A800 to SFT：
bash exps/paper_exps/SFT/gsm8k.sh ，but CUDA out of memory：
rank0]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1885, in step
[rank0]:     int(self.partition_size[i])).to(self.single_partition_of_fp32_groups[i].dtype)
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 25.10 GiB. GPU 

The batch size are:
batch_size="1"
eval_batch_size="1"

**Comment by lqtrung1998** [comment]
Hi @rxmao ,

Our experiment was done with 8-A100 GPUs. 

Some optimizations (e.g Zero-3 + offloading) may be applied to lower memory requirement

Best Regards,
Trung
