### ISSUE TITLE
About bash exps/small_model_exps/rl_gsm8k.sh 

### ISSUE THREAD

**Issue by rxmao** [lqtrung1998/mwp_ReFT#13]
A bug:
[rank4]: OSError: Incorrect path_or_model_id: 'ppo_paper_final_new/_models_outputs_sft_small/gsm8k_python_sdp_galactica_125m/global_step_1540_epoch_10/'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by lqtrung1998** [comment]
Hi @rxmao ,
The checkpoint can be obtained by using this script: ```https://github.com/lqtrung1998/mwp_ReFT/blob/main/exps/small_model_exps/sft_gsm8k.sh```

**Comment by rxmao** [comment]
soloved
