### ISSUE TITLE
Checkpoints not available

### ISSUE THREAD

**Issue by boyugou** [lqtrung1998/mwp_ReFT#2]
Both https://huggingface.co/lqtrung1998/Codellama-7b-hf-ReFT-GSM8k and https://huggingface.co/lqtrung1998/Codellama-7b-hf-ReFT-Rerank-GSM8k are not available currently.

**Comment by lqtrung1998** [comment]
Hi @boyugou,
Thank you for your interest, we have made those checkpoints public and also released a few more. 

Please look at the README page for the updated links. 

Best Regards,
Trung
