### ISSUE TITLE
Any plans to release models for SVAMP and MathQA?

### ISSUE THREAD

**Issue by conglu1997** [lqtrung1998/mwp_ReFT#7]
Hope you are doing well! 

I was wondering if there were any plans to release the SFT base/ReFT models for SVAMP and MathQA for reproducing the results in Table 2? 

Thanks so much!

**Comment by lqtrung1998** [comment]
Hi @conglu1997,

Unfortunately, we don't have plan to release SFT base/ReFT models for SVAMP and MathQA. But I can help if you have any problem reproducing the result in Table 2.

Best Regards,
Trung
